sudo: required
dist: xenial

services:
- docker

env:
  global:
    - IMAGE_NAME: $TRAVIS_REPO_SLUG
    - IMAGE_VERSION: $TRAVIS_TAG
    - secure: "KHqyvWNQBErMiS5XK0J/2DOey7jsTGAk67DOqOYi1fXzBBwfd/MER6dZZnnMNApjJdYDiXjr2cHkarufk7v++f48/CYR8zADQHF5RWSQUvWF63W49tbYBm6XrEsFmW1eWfAJlT/WUIF6nWc2VfVutHGoN2ABRilrAsN7yhBEp5MadRws754mqdOxUwWdlIwBq1tTe1QaPJVes8E/uOlhlcebzSPOzWPHBo8j1yWc/Wef6uEToXPzV816SBdkOynlxblyWyEOcg1Z5C/tPcRmuZodx5E58GRLdsKN5c1v2dfIozjMlC8VYYQykwk/WbuI9LBDk/oEMXEsYGj0MHCbhUJWiF6QuNz4ERZrdF48Pe6+ZT1tNFtXuVfDPMfNmUTKWOMbBlWNNb7BKCUmU1cJvUCIwr5a5QTBU+Kbc9ry+M4Fshzu+DraX45wqlI9Dqucd9QFM7HPIQyoLkRF/DnqV1TMgXs2QBDlf7dn1ERVOl6eFZWo5J2qKj0hrttSf+Z3x1kqF+nN/Krz1GbYBhPIt8kelgor5YbP5EEmBxqJCBRkPm6uOpG1UcxEOI9T6ESsJzczkYrwefpdY3VHw02YYbSmKdHiWZRfG/Q9BmZDF/gnKcrhW1Mr7p9HnpFrKXJUB2yLeUPOO/AHOocYwyPMWAUj+FXzf7a6KVx5Sih/5/E="
    - secure: "a6ig+9uMxlDRb1u2GHBbErgmSJ/X1pMQn5Ipq04C+hV8FOny2gl0J/b76MRgezWqFyv08wLZvuoj7INC5tTSjAFYHdVS1Gl7gyCj9CmkdBJwsaDESAWVDNDEIdYMXDIZflx+KlZhQMGI20WQSY8dQbB3oywb+2ODbBWyBuK/48yPiu2Wbbj2txyGQYQ9WOlAEqxASjHbeejV608dyO/Z8/9HUgtLTKmGyuBo+1/cSCHC25kdGM2jPwUYTcrr050esTxFoQBQ/uOg3b4tqoI6kngkeQ64AywDILbZe19M92x2XNNIy58KyyPRyMHsjN9XTdxqukRr/qlFtRcsGxua52L/NbOJtU5IH3pU7BhYi+o1eNbh5r2r4nKu5WKAeirED188XRtzTOxJjWNsLqwZ25TOpUJ8vpISKWSlrMUhaHgQYof+1wSs1sF4Mu0yqA2bw7dBuThSjUonRsBnoSrY8hX/ge+9rRi7TmWjy0kyi6B/2sWxRmznsI3MKffDAapFMje50p4DkRnQ2BWnLo1/dzGq2odRDc3gF/tbY8IKogF0tg43egqyg+WO3+VGFepCRNGnpxj8PtaMIFuGkQgeMKTRG+ugSSSnJPaSLUBcYsnIKq4zhI4kHg036YpD/BSf85OtH3HzKcaKaUHwAOo5CI/mo/CrtTpbu8AHjgFxJHg="
language: python

python:
- '3.6'

install:
- pip install flake8
- pip install coveralls

script:
- flake8 .

after_success:
- coveralls

before_deploy:
- python setup.py bdist_wheel

deploy:
- provider: pypi
  user: adalekin
  password:
    secure: FEHXDGiBHN0qX4gZ0UTj3WQXuOZpAnafWLNQTwcjKlufTHERRIra2QhhqBgoeIAPLnZqcUVx+hpROuDPa8d0rGY3+MegJBucwQq5eev2Ui/0WCx7UlO2KLbPKUw9J63XMvVDnwiWK58dQGkAceI53c7YPTNt0poyqmlWBVyHgp7McXZUWOt53a6nwxQTnz3fIotBNSHxdpseQsldi3YQJE94vLijX3d32cZZK5s3/GNaxiIQf+Ujdc7Sl5azfQ9cGE3DsfxFno/VsupYR3wc5BHfoIBvHYvyKG9P0CFUPQU0764X0dpBbj1wgIK7m7RAGeNzUu0l9mD17uY6ANYiy5SfHmn3MfuyOMPv72LXiOxrOSPb4K237TpUT513FBkI5h5v22pMa2q1mfvvP2NaMBnQS+NEMxo6bb8Wwd7VQzsobfpDSWZKylPbUox75hTp/a8swrhbcbtYpD0e95a/lonlMfhqSo/p5rFwGpLa2ugHzqqy+zy4P4OCod3UEM6NCdKoh8deqvI+5LGLLgVs1GoeICq4qR6W37A49X0Plqlf1i8hJvdweVJ8zBaHwCxO21k1HINj3pM4BdihlEq1n6sUD5qxQmhOEPh0UUb175j05rlu/BHEh45/QuxHmtQG3pexnof7We13jXQ7C2QwKdnTOMOM/Lt8ciTDlKYKI90=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6

after_deploy:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t "${IMAGE_NAME}:${IMAGE_VERSION}" .
- docker push "${IMAGE_NAME}:${IMAGE_VERSION}"
